name: Build Test

on:
  push:
    branches:
      - "*"

jobs:
  setup:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Ubuntu Dependencies
        run: chmod +x ./setup-ubuntu.sh && ./setup-ubuntu.sh
      
      - name: Dotnet version
        run: dotnet --version

  mvc-core:
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - name: Run mvc Script
        run: chmod +x ./workflow-run-booktok.sh && ./workflow-run-booktok.sh 

