name: Build Test

on:
  push:
    branches:
      - "*"

jobs:
  setup:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Ubuntu Dependencies
        run: chmod +x ./setup-ubuntu.sh && ./setup-ubuntu.sh
      
      - name: Dotnet version
        run: dotnet --version

  mvc-core:
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - uses: actions/checkout@v4
      
      - run: cd ./BookTok

      - name: Intall Dependencies
        run: chmod +x ./install-dependencies.sh && ./install-dependencies.sh

      - name: Build
        run: dotnet build


  api:
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - uses: actions/checkout@v4
      
      - run: cd ./BookTokApi

      - name: Intall Dependencies
        run: chmod +x ./install-dependencies.sh && ./install-dependencies.sh

      - name: Build
        run: dotnet build

      - name: Run Project
        run: nohup dotnet run > /dev/null 2>&1 &

      - name: Test Endpoints
        run: chmod +x test-endpoints.sh && ./test-endpoints.sh

        

